/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 computer.gltf 
Author: arthursamuel (https://sketchfab.com/arthursamuel)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/computer-957d4cfd857d45d8a112088eba4ad5aa
Title: Computer
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/computer.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0.349, 1.382, -0.131]} rotation={[0.023, 0, 0]} scale={0.065}>
            <mesh geometry={nodes.blinn7.geometry} material={materials.blinn7} />
            <mesh geometry={nodes.blinn8.geometry} material={materials.blinn8} />
            <mesh geometry={nodes.blinn10.geometry} material={materials.blinn10} />
            <mesh geometry={nodes.blinn9.geometry} material={materials.blinn9} />
          </group>
          <group position={[1.285, 1.379, -0.228]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.044, 0.002, 0.041]}>
            <mesh geometry={nodes.phongE2.geometry} material={materials.phongE2} />
            <mesh geometry={nodes.blinn4.geometry} material={materials.blinn4} />
            <mesh geometry={nodes.blinn6.geometry} material={materials.blinn6} />
          </group>
          <group position={[1.644, 0.746, -0.216]} scale={[0.397, 0.908, 0.888]}>
            <mesh geometry={nodes.blinn3.geometry} material={materials.blinn3} />
            <mesh geometry={nodes.anisotropic3.geometry} material={materials.anisotropic3} />
            <mesh geometry={nodes.anisotropic2.geometry} material={materials.anisotropic2} />
          </group>
          <group position={[1.268, 0.972, -0.331]} rotation={[0, -0.181, 0]} scale={0.627}>
            <mesh geometry={nodes.blinn1.geometry} material={materials.blinn1} />
            <mesh geometry={nodes.blinn17.geometry} material={materials.blinn17} />
            <mesh geometry={nodes.phong2.geometry} material={materials.phong2} />
            <mesh geometry={nodes.lambert1.geometry} material={materials.lambert1} />
            <mesh geometry={nodes.anisotropic1.geometry} material={materials.anisotropic1} />
            <mesh geometry={nodes.phong1.geometry} material={materials.phong1} />
          </group>
          <group position={[-5.423, -0.733, 0]}>
            <mesh geometry={nodes.blinn15.geometry} material={materials.blinn15} />
            <mesh geometry={nodes.blinn16.geometry} material={materials.blinn16} />
          </group>
          <group position={[0.118, 0.972, -0.336]} rotation={[0, 0.136, 0]} scale={0.627}>
            <mesh geometry={nodes.blinn1_1.geometry} material={materials.blinn1} />
            <mesh geometry={nodes.blinn18.geometry} material={materials.blinn18} />
            <mesh geometry={nodes.phong2_1.geometry} material={materials.phong2} />
            <mesh geometry={nodes.lambert1_1.geometry} material={materials.lambert1} />
            <mesh geometry={nodes.anisotropic1_1.geometry} material={materials.anisotropic1} />
            <mesh geometry={nodes.phong1_1.geometry} material={materials.phong1} />
          </group>
          <mesh geometry={nodes.anisotropic7.geometry} material={materials.anisotropic7} position={[-1.071, 2.149, 0]} rotation={[0, 0.38, 0]} scale={0.106} />
          <mesh geometry={nodes.phongE1.geometry} material={materials.phongE1} position={[0.545, 0.907, -0.102]} scale={0.598} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/computer.gltf')
